// Gallery sidebar navigation — pure data, no React/next imports so it can be
// imported by Node's `--test` runner for the slug-consistency gate
// (tests/gallery-slug-consistency.test.ts). app/gallery/layout.tsx renders it.

export interface NavItem {
  label: string
  slug: string
}

export interface NavGroup {
  group: string
  items: NavItem[]
}

export const NAV: NavGroup[] = [
  { group: "Foundations", items: [
    { label: "Color tokens", slug: "colors" },
    { label: "Typography", slug: "type" },
    { label: "Spacing & radii", slug: "spacing" },
    { label: "Brand & mark", slug: "brand" },
    { label: "Direction", slug: "direction" },
  ]},
  { group: "Controls", items: [
    { label: "Buttons", slug: "buttons" },
    { label: "Button group", slug: "button-group" },
    { label: "Badges", slug: "badges" },
    { label: "Toggle switch", slug: "switch" },
    { label: "Toggle", slug: "toggle" },
    { label: "Toggle group", slug: "toggle-group" },
    { label: "Avatar", slug: "avatar" },
    { label: "Progress", slug: "progress" },
    { label: "Spinner", slug: "spinner" },
    { label: "Separator", slug: "separator" },
    { label: "Toolbar", slug: "toolbar" },
    { label: "Kbd", slug: "kbd" },
  ]},
  { group: "Form elements", items: [
    { label: "Inputs & selects", slug: "forms" },
    { label: "Input", slug: "input" },
    { label: "Field", slug: "field" },
    { label: "Label", slug: "label" },
    { label: "Input group", slug: "input-group" },
    { label: "Input OTP", slug: "input-otp" },
    { label: "Native select", slug: "native-select" },
    { label: "Select", slug: "select" },
    { label: "Combobox", slug: "combobox" },
    { label: "Checkbox & radio", slug: "checkboxes" },
    { label: "Radio group", slug: "radio-group" },
    { label: "Slider", slug: "slider" },
    { label: "Number input", slug: "number-input" },
    { label: "Textarea", slug: "textarea" },
    { label: "Calendar", slug: "calendar" },
    { label: "Date picker", slug: "date-picker" },
    { label: "Tabs & pills", slug: "tabs" },
  ]},
  { group: "Feedback", items: [
    { label: "Alert", slug: "alert" },
    { label: "Banners", slug: "banners" },
    { label: "Callout", slug: "callout" },
    { label: "Toasts", slug: "toasts" },
    { label: "Sonner", slug: "sonner" },
    { label: "Tooltip", slug: "tooltip" },
    { label: "Empty states", slug: "empty" },
    { label: "Skeleton", slug: "skeleton" },
    { label: "Status indicator", slug: "status-indicator" },
    { label: "Shimmer", slug: "shimmer" },
    { label: "Confirmation", slug: "confirmation" },
  ]},
  { group: "Navigation", items: [
    { label: "Breadcrumb", slug: "breadcrumb" },
    { label: "Pagination", slug: "pagination" },
    { label: "Command", slug: "command" },
    { label: "Navigation menu", slug: "navigation-menu" },
    { label: "Menubar", slug: "menubar" },
  ]},
  { group: "Data", items: [
    { label: "Stat cards", slug: "stats" },
    { label: "Tables", slug: "tables" },
    { label: "Data table", slug: "data-table" },
    { label: "Filter bars", slug: "filters" },
    { label: "Timeline", slug: "timeline" },
    { label: "Description list", slug: "description-list" },
    { label: "Search results", slug: "search-results" },
    { label: "Listbox", slug: "listbox" },
    { label: "Marketplace", slug: "marketplace" },
  ]},
  { group: "Overlays", items: [
    { label: "Modal & dialog", slug: "modals" },
    { label: "Alert dialog", slug: "alert-dialog" },
    { label: "Accordion", slug: "accordion" },
    { label: "Collapsible", slug: "collapsible" },
    { label: "Dropdowns", slug: "dropdowns" },
    { label: "Context menu", slug: "context-menu" },
    { label: "Popover", slug: "popover" },
    { label: "Hover card", slug: "hover-card" },
    { label: "Sheet", slug: "sheet" },
    { label: "Drawer", slug: "drawer" },
    { label: "Share dialog", slug: "share-dialog" },
  ]},
  { group: "Chat & AI", items: [
    { label: "Prompt input", slug: "prompt-input" },
    { label: "AI elements", slug: "ai-elements" },
    { label: "Message", slug: "message" },
    { label: "Conversation", slug: "conversation" },
    { label: "Model selector", slug: "model-selector" },
    { label: "Persona", slug: "persona" },
    { label: "Open in chat", slug: "open-in-chat" },
    { label: "Reasoning", slug: "reasoning" },
    { label: "Tool calls", slug: "tool-calls" },
    { label: "Tool", slug: "tool" },
    { label: "Thinking", slug: "thinking" },
    { label: "Chain of thought", slug: "chain-of-thought" },
    { label: "Plan", slug: "plan" },
    { label: "Task", slug: "task" },
    { label: "Queue", slug: "queue" },
    { label: "Suggestion", slug: "suggestion" },
    { label: "Code block", slug: "code-block" },
    { label: "Artifact", slug: "artifact" },
    { label: "Terminal", slug: "terminal" },
    { label: "Permission prompt", slug: "permission-prompt" },
    { label: "Ask user question", slug: "ask-user-question" },
    { label: "Permissions config", slug: "permissions-dropdown" },
    { label: "Command palette", slug: "command-palette" },
    { label: "Sidebar", slug: "sidebar" },
  ]},
  { group: "Runtime & execution", items: [
    { label: "Agent", slug: "agent" },
    { label: "Checkpoint", slug: "checkpoint" },
    { label: "Commit", slug: "commit" },
    { label: "Context panel", slug: "context" },
    { label: "Environment variables", slug: "environment-variables" },
    { label: "Package info", slug: "package-info" },
    { label: "Schema display", slug: "schema-display" },
    { label: "Sandbox", slug: "sandbox" },
    { label: "Snippet", slug: "snippet" },
    { label: "JSX preview", slug: "jsx-preview" },
    { label: "Stack trace", slug: "stack-trace" },
    { label: "Test results", slug: "test-results" },
    { label: "Panel", slug: "panel" },
    { label: "Control strip", slug: "controls" },
    { label: "Canvas", slug: "canvas" },
    { label: "Connection", slug: "connection" },
    { label: "Edge", slug: "edge" },
    { label: "Node", slug: "node" },
  ]},
  { group: "Media & voice", items: [
    { label: "Audio player", slug: "audio-player" },
    { label: "Mic selector", slug: "mic-selector" },
    { label: "Speech input", slug: "speech-input" },
    { label: "Transcription", slug: "transcription" },
    { label: "Voice selector", slug: "voice-selector" },
  ]},
  { group: "Content", items: [
    { label: "Attachment chip", slug: "attachment" },
    { label: "AI attachments", slug: "attachments" },
    { label: "Sources", slug: "sources" },
    { label: "Inline citation", slug: "inline-citation" },
    { label: "File picker", slug: "file-picker" },
    { label: "File tree", slug: "file-tree" },
    { label: "Code editor", slug: "code-editor" },
    { label: "Web preview", slug: "web-preview" },
    { label: "Aspect ratio", slug: "aspect-ratio" },
    { label: "Card", slug: "card" },
    { label: "Carousel", slug: "carousel" },
    { label: "Chart", slug: "chart" },
    { label: "Image", slug: "image" },
    { label: "Item", slug: "item" },
    { label: "Resizable panels", slug: "resizable-panels" },
    { label: "Scroll area", slug: "scroll-area" },
  ]},
  { group: "Auth & Errors", items: [
    { label: "Login", slug: "login" },
    { label: "OAuth flow", slug: "oauth" },
    { label: "Error pages", slug: "error-pages" },
  ]},
  { group: "Themes", items: [
    { label: "Light mode", slug: "lightmode" },
  ]},
  { group: "AI elements (new)", items: [
    { label: "Action", slug: "action" },
    { label: "Actions", slug: "actions" },
    { label: "AiImageGrid", slug: "ai-image-grid" },
    { label: "Branch", slug: "branch" },
    { label: "Loader", slug: "loader" },
    { label: "MessageAvatar", slug: "message-avatar" },
    { label: "MessageContent", slug: "message-content" },
    { label: "Response", slug: "response" },
    { label: "Source", slug: "source" },
  ]},
  { group: "Aurora extensions", items: [
    { label: "ChatMessage", slug: "chat-message" },
    { label: "ChatSidebar", slug: "chat-sidebar" },
    { label: "ColorPicker", slug: "color-picker" },
    { label: "ComponentCard", slug: "component-card" },
    { label: "CopyButton", slug: "copy-button" },
    { label: "MultiSelect", slug: "multi-select" },
    { label: "OperationIcon", slug: "operation-icon" },
    { label: "ProgressRing", slug: "progress-ring" },
    { label: "RangeSlider", slug: "range-slider" },
    { label: "Rating", slug: "rating" },
    { label: "Segmented", slug: "segmented" },
    { label: "Spotlight", slug: "spotlight" },
    { label: "StatusDot", slug: "status-dot" },
    { label: "Stepper", slug: "stepper" },
    { label: "TagInput", slug: "tag-input" },
  ]},
]

export const NAV_SLUG_ALIASES: Record<string, string> = {
  tokens: "colors",
  typography: "type",
  button: "buttons",
  badge: "badges",
  banner: "banners",
  toast: "toasts",
  "empty-state": "empty",
  "stat-card": "stats",
  "filter-bar": "filters",
  dialog: "modals",
  "dropdown-menu": "dropdowns",
  "error-page": "error-pages",
}
