import * as React from "react"
import { notFound } from "next/navigation"
import dynamic from "next/dynamic"

const COMPONENT_DEMOS: Record<string, React.ComponentType> = {
  alert: dynamic(() => import("../demos/alert-demo")),
  "alert-dialog": dynamic(() => import("../demos/alert-dialog-demo")),
  "aspect-ratio": dynamic(() => import("../demos/aspect-ratio-demo")),
  calendar: dynamic(() => import("../demos/calendar-demo")),
  card: dynamic(() => import("../demos/card-demo")),
  carousel: dynamic(() => import("../demos/carousel-demo")),
  chart: dynamic(() => import("../demos/chart-demo")),
  collapsible: dynamic(() => import("../demos/collapsible-demo")),
  command: dynamic(() => import("../demos/command-demo")),
  "data-table": dynamic(() => import("../demos/data-table-demo")),
  "date-picker": dynamic(() => import("../demos/date-picker-demo")),
  direction: dynamic(() => import("../demos/direction-demo")),
  drawer: dynamic(() => import("../demos/drawer-demo")),
  field: dynamic(() => import("../demos/field-demo")),
  "hover-card": dynamic(() => import("../demos/hover-card-demo")),
  input: dynamic(() => import("../demos/input-demo")),
  "input-group": dynamic(() => import("../demos/input-group-demo")),
  "input-otp": dynamic(() => import("../demos/input-otp-demo")),
  item: dynamic(() => import("../demos/item-demo")),
  label: dynamic(() => import("../demos/label-demo")),
  menubar: dynamic(() => import("../demos/menubar-demo")),
  "native-select": dynamic(() => import("../demos/native-select-demo")),
  "navigation-menu": dynamic(() => import("../demos/navigation-menu-demo")),
  popover: dynamic(() => import("../demos/popover-demo")),
  "radio-group": dynamic(() => import("../demos/radio-group-demo")),
  resizable: dynamic(() => import("../demos/resizable-demo")),
  "scroll-area": dynamic(() => import("../demos/scroll-area-demo")),
  select: dynamic(() => import("../demos/select-demo")),
  slider: dynamic(() => import("../demos/slider-demo")),
  sonner: dynamic(() => import("../demos/sonner-demo")),
  table: dynamic(() => import("../demos/table-demo")),
  textarea: dynamic(() => import("../demos/textarea-demo")),
  toggle: dynamic(() => import("../demos/toggle-demo")),
  "toggle-group": dynamic(() => import("../demos/toggle-group-demo")),
  typography: dynamic(() => import("../demos/typography-demo")),
  "number-input": dynamic(() => import("../demos/number-input-demo")),
  combobox: dynamic(() => import("../demos/combobox-demo")),
  sheet: dynamic(() => import("../demos/sheet-demo")),
  callout: dynamic(() => import("../demos/callout-demo")),
  "status-indicator": dynamic(() => import("../demos/status-indicator-demo")),
  timeline: dynamic(() => import("../demos/timeline-demo")),
  "description-list": dynamic(() => import("../demos/description-list-demo")),
  "resizable-panels": dynamic(() => import("../demos/resizable-panels-demo")),
  listbox: dynamic(() => import("../demos/listbox-demo")),
  "search-results": dynamic(() => import("../demos/search-results-demo")),
  kbd: dynamic(() => import("../demos/kbd-demo")),
  toolbar: dynamic(() => import("../demos/toolbar-demo")),
}

const AI_DEMOS: Record<string, React.ComponentType> = {
  attachments: dynamic(() => import("../demos/ai-attachments-demo")),
  "chain-of-thought": dynamic(() => import("../demos/ai-chain-of-thought-demo")),
  checkpoint: dynamic(() => import("../demos/ai-checkpoint-demo")),
  confirmation: dynamic(() => import("../demos/ai-confirmation-demo")),
  context: dynamic(() => import("../demos/ai-context-demo")),
  conversation: dynamic(() => import("../demos/ai-conversation-demo")),
  "inline-citation": dynamic(() => import("../demos/ai-inline-citation-demo")),
  message: dynamic(() => import("../demos/ai-message-demo")),
  "model-selector": dynamic(() => import("../demos/ai-model-selector-demo")),
  plan: dynamic(() => import("../demos/ai-plan-demo")),
  queue: dynamic(() => import("../demos/ai-queue-demo")),
  reasoning: dynamic(() => import("../demos/ai-reasoning-demo")),
  shimmer: dynamic(() => import("../demos/ai-shimmer-demo")),
  sources: dynamic(() => import("../demos/ai-sources-demo")),
  suggestion: dynamic(() => import("../demos/ai-suggestion-demo")),
  task: dynamic(() => import("../demos/ai-task-demo")),
  tool: dynamic(() => import("../demos/ai-tool-demo")),
  agent: dynamic(() => import("../demos/ai-agent-demo")),
  commit: dynamic(() => import("../demos/ai-commit-demo")),
  "environment-variables": dynamic(() => import("../demos/ai-environment-variables-demo")),
  "jsx-preview": dynamic(() => import("../demos/ai-jsx-preview-demo")),
  "package-info": dynamic(() => import("../demos/ai-package-info-demo")),
  sandbox: dynamic(() => import("../demos/ai-sandbox-demo")),
  "schema-display": dynamic(() => import("../demos/ai-schema-display-demo")),
  snippet: dynamic(() => import("../demos/ai-snippet-demo")),
  "stack-trace": dynamic(() => import("../demos/ai-stack-trace-demo")),
  "test-results": dynamic(() => import("../demos/ai-test-results-demo")),
  "audio-player": dynamic(() => import("../demos/ai-audio-player-demo")),
  "mic-selector": dynamic(() => import("../demos/ai-mic-selector-demo")),
  persona: dynamic(() => import("../demos/ai-persona-demo")),
  "speech-input": dynamic(() => import("../demos/ai-speech-input-demo")),
  transcription: dynamic(() => import("../demos/ai-transcription-demo")),
  "voice-selector": dynamic(() => import("../demos/ai-voice-selector-demo")),
  canvas: dynamic(() => import("../demos/ai-canvas-demo")),
  connection: dynamic(() => import("../demos/ai-connection-demo")),
  controls: dynamic(() => import("../demos/ai-controls-demo")),
  edge: dynamic(() => import("../demos/ai-edge-demo")),
  node: dynamic(() => import("../demos/ai-node-demo")),
  panel: dynamic(() => import("../demos/ai-panel-demo")),
  image: dynamic(() => import("../demos/ai-image-demo")),
  "open-in-chat": dynamic(() => import("../demos/ai-open-in-chat-demo")),
}

const AI_CANONICAL_DEMOS: Record<string, React.ComponentType> = Object.fromEntries(
  Object.entries(AI_DEMOS).map(([slug, Demo]) => [`ai-${slug}`, Demo])
)

const DEMOS: Record<string, React.ComponentType> = {
  ...COMPONENT_DEMOS,
  ...AI_DEMOS,
  ...AI_CANONICAL_DEMOS,
  tokens:      dynamic(() => import("../demos/colors-demo")),
  colors:      dynamic(() => import("../demos/colors-demo")),
  type:        dynamic(() => import("../demos/type-demo")),
  spacing:     dynamic(() => import("../demos/spacing-demo")),
  brand:       dynamic(() => import("../demos/brand-demo")),
  button:      dynamic(() => import("../demos/buttons-demo")),
  buttons:     dynamic(() => import("../demos/buttons-demo")),
  "button-group": dynamic(() => import("../demos/button-group-demo")),
  badge:       dynamic(() => import("../demos/badges-demo")),
  badges:      dynamic(() => import("../demos/badges-demo")),
  switch:      dynamic(() => import("../demos/switch-demo")),
  avatar:      dynamic(() => import("../demos/avatar-demo")),
  progress:    dynamic(() => import("../demos/progress-demo")),
  spinner:     dynamic(() => import("../demos/spinner-demo")),
  separator:   dynamic(() => import("../demos/separator-demo")),
  forms:       dynamic(() => import("../demos/forms-demo")),
  checkbox:    dynamic(() => import("../demos/checkboxes-demo")),
  checkboxes:  dynamic(() => import("../demos/checkboxes-demo")),
  tabs:        dynamic(() => import("../demos/tabs-demo")),
  banner:      dynamic(() => import("../demos/banners-demo")),
  banners:     dynamic(() => import("../demos/banners-demo")),
  toast:       dynamic(() => import("../demos/toasts-demo")),
  toasts:      dynamic(() => import("../demos/toasts-demo")),
  tooltip:     dynamic(() => import("../demos/tooltip-demo")),
  "empty-state": dynamic(() => import("../demos/empty-demo")),
  empty:       dynamic(() => import("../demos/empty-demo")),
  skeleton:    dynamic(() => import("../demos/skeleton-demo")),
  breadcrumb:  dynamic(() => import("../demos/breadcrumb-demo")),
  pagination:  dynamic(() => import("../demos/pagination-demo")),
  "stat-card": dynamic(() => import("../demos/stats-demo")),
  stats:       dynamic(() => import("../demos/stats-demo")),
  tables:      dynamic(() => import("../demos/tables-demo")),
  "filter-bar": dynamic(() => import("../demos/filters-demo")),
  filters:     dynamic(() => import("../demos/filters-demo")),
  marketplace: dynamic(() => import("../demos/marketplace-demo")),
  "new-components": dynamic(() => import("../demos/new-components-demo")),
  dialog:      dynamic(() => import("../demos/modals-demo")),
  modals:      dynamic(() => import("../demos/modals-demo")),
  accordion:   dynamic(() => import("../demos/accordion-demo")),
  "dropdown-menu": dynamic(() => import("../demos/dropdowns-demo")),
  dropdowns:   dynamic(() => import("../demos/dropdowns-demo")),
  "context-menu": dynamic(() => import("../demos/context-menu-demo")),
  "prompt-input": dynamic(() => import("../demos/prompt-input-demo")),
  "ai-elements":   dynamic(() => import("../demos/ai-elements-demo")),
  "tool-calls":   dynamic(() => import("../demos/tool-calls-demo")),
  thinking:       dynamic(() => import("../demos/thinking-demo")),
  "code-block":   dynamic(() => import("../demos/code-block-demo")),
  artifact:       dynamic(() => import("../demos/artifact-demo")),
  terminal:       dynamic(() => import("../demos/terminal-demo")),
  "permission-prompt":    dynamic(() => import("../demos/permission-prompt-demo")),
  "ask-user-question":    dynamic(() => import("../demos/ask-user-question-demo")),
  "permissions-dropdown": dynamic(() => import("../demos/permissions-dropdown-demo")),
  attachment:     dynamic(() => import("../demos/attachment-demo")),
  "command-palette": dynamic(() => import("../demos/command-palette-demo")),
  sidebar:        dynamic(() => import("../demos/sidebar-demo")),
  "file-picker":  dynamic(() => import("../demos/file-picker-demo")),
  "file-tree":    dynamic(() => import("../demos/file-tree-demo")),
  "code-editor":  dynamic(() => import("../demos/code-editor-demo")),
  "web-preview":  dynamic(() => import("../demos/web-preview-demo")),
  "share-dialog": dynamic(() => import("../demos/share-dialog-demo")),
  login:          dynamic(() => import("../demos/login-demo")),
  oauth:          dynamic(() => import("../demos/oauth-demo")),
  "error-page":   dynamic(() => import("../demos/error-pages-demo")),
  "error-pages":  dynamic(() => import("../demos/error-pages-demo")),
  lightmode:      dynamic(() => import("../demos/lightmode-demo")),
}

export function generateStaticParams() {
  return Object.keys(DEMOS).map((section) => ({ section }))
}

export default async function SectionPage({ params }: { params: Promise<{ section: string }> }) {
  const { section } = await params
  const Demo = DEMOS[section]
  if (!Demo) notFound()
  return <Demo />
}
