package tv.tootie.aurora.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.ProvidableCompositionLocal
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color
import tv.tootie.aurora.tokens.AuroraColors

@Immutable
public data class AuroraExtraColors(
    val accentPink: Color,
    val accentPinkSurface: Color,
    val accentPinkBorder: Color,
    val accentPinkButton: Color,
    val axonOrange: Color,
    val axonOrangeStrong: Color,
    val axonOrangeDeep: Color,
    val axonOrangeButton: Color,
    val axonOrangeSurface: Color,
    val axonOrangeBorder: Color,
    val accentViolet: Color,
    val accentVioletSurface: Color,
    val accentVioletBorder: Color,
    val accentVioletButton: Color,
    val success: Color,
    val successSurface: Color,
    val successBorder: Color,
    val successForeground: Color,
    val warn: Color,
    val warnSurface: Color,
    val warnBorder: Color,
    val warnForeground: Color,
    val info: Color,
    val infoSurface: Color,
    val infoBorder: Color,
    val infoForeground: Color,
    val neutral: Color,
    val neutralSurface: Color,
    val neutralBorder: Color,
    val neutralForeground: Color,
    val error: Color,
    val errorSurface: Color,
    val errorBorder: Color,
    val errorForeground: Color,
    val borderDefault: Color,
    val borderStrong: Color,
    val hoverBg: Color,
    val subtleBg: Color,
    val selectedBg: Color,
    val pressedBg: Color,
    val disabledText: Color,
    val disabledSurface: Color,
    val overlay: Color,
    val focusRing: Color,
    val focusRingStrong: Color,
    val codeType: Color,
    val codeFunction: Color,
)

// Dark theme snapshot — used as default for LocalAuroraColors
// so Compose Previews render correctly even without AuroraTheme{}
public val DarkAuroraExtraColors: AuroraExtraColors = AuroraExtraColors(
    accentPink = AuroraColors.accentPinkBase,
    accentPinkSurface = AuroraColors.accentPinkSurface,
    accentPinkBorder = AuroraColors.accentPinkBorder,
    accentPinkButton = AuroraColors.accentPinkButton,
    axonOrange = AuroraColors.axonOrangeBase,
    axonOrangeStrong = AuroraColors.axonOrangeStrong,
    axonOrangeDeep = AuroraColors.axonOrangeDeep,
    axonOrangeButton = AuroraColors.axonOrangeButton,
    axonOrangeSurface = AuroraColors.axonOrangeSurface,
    axonOrangeBorder = AuroraColors.axonOrangeBorder,
    // Compatibility aliases for existing AI component call sites.
    accentViolet = AuroraColors.axonOrangeBase,
    accentVioletSurface = AuroraColors.axonOrangeSurface,
    accentVioletBorder = AuroraColors.axonOrangeBorder,
    accentVioletButton = AuroraColors.axonOrangeButton,
    success = AuroraColors.successBase,
    successSurface = AuroraColors.successSurface,
    successBorder = AuroraColors.successBorder,
    successForeground = AuroraColors.successForeground,
    warn = AuroraColors.warnBase,
    warnSurface = AuroraColors.warnSurface,
    warnBorder = AuroraColors.warnBorder,
    warnForeground = AuroraColors.warnForeground,
    info = AuroraColors.infoBase,
    infoSurface = AuroraColors.infoSurface,
    infoBorder = AuroraColors.infoBorder,
    infoForeground = AuroraColors.infoForeground,
    neutral = AuroraColors.neutralBase,
    neutralSurface = AuroraColors.neutralSurface,
    neutralBorder = AuroraColors.neutralBorder,
    neutralForeground = AuroraColors.neutralForeground,
    error = AuroraColors.errorBase,
    errorSurface = AuroraColors.errorSurface,
    errorBorder = AuroraColors.errorBorder,
    errorForeground = AuroraColors.errorForeground,
    borderDefault = AuroraColors.borderDefault,
    borderStrong = AuroraColors.borderStrong,
    hoverBg = AuroraColors.hoverBg,
    subtleBg = AuroraColors.subtleBg,
    selectedBg = AuroraColors.selectedBg,
    pressedBg = AuroraColors.pressedBg,
    disabledText = AuroraColors.disabledText,
    disabledSurface = AuroraColors.disabledSurface,
    overlay = AuroraColors.overlay,
    focusRing = AuroraColors.focusRingBase,
    focusRingStrong = AuroraColors.focusRingStrong,
    codeType = AuroraColors.codeType,
    codeFunction = AuroraColors.codeFunction,
)

public val LocalAuroraColors: ProvidableCompositionLocal<AuroraExtraColors> = staticCompositionLocalOf { DarkAuroraExtraColors }
